### ISSUE TITLE
Sideways scrolling in Safari

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#693] opened 2016-05-13 08:59 UTC
On Safari, I notice that you can scroll sideways to the right on the homepage. I think it is because of the picture of the hand and the pencil is larger than the width the homepage is set to.

It looks like this.
[isaac to the side.pdf](https://github.com/ucam-cl-dtg/isaac-app/files/262858/isaac.to.the.side.pdf)

**Comment by jsharkey13** [comment] 2016-05-13 09:31
This is a duplicate of https://github.com/ucam-cl-dtg/isaac-app/issues/669 and it's not the images that are the problem per se. I can have another look.

**Closed** 2017-05-08 15:19 UTC
