### ISSUE TITLE
Infinite events if all events selected

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#588] opened 2015-10-23 16:17 UTC
On staging, with "Upcoming Events" and "All Events" selected in the drop-down box, clicking more events multiple times duplicates the latest 4 events over and over again.

Console gives "TypeError: Cannot set property 'src' of undefined" error

**Comment by jsharkey13** [comment] 2015-10-23 16:18
Also, the drop down box gets a funky blank item added when you use the url to show virtual events:
![image](https://cloud.githubusercontent.com/assets/8060558/10698660/0fdcfa90-79aa-11e5-835e-500a1b030112.png)

It's probably related . . .

**Comment by sacummins** [comment] 2015-10-26 12:42
Please raise the blank dropdown box separately. 

The infinite event list is caused by a malformed event not having an eventThumbnail. This should be corrected. This will be fixed in the next release in Commit e95c1503bfca9a93fa6344be3518a378483234b6

**Closed by sacummins** 2015-10-26 12:42 UTC
Labels: bug
