### ISSUE TITLE
Two additional links from teacher modal

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#463] opened 2015-07-28 13:46 UTC
There are two parts of the teacher modal that don't currently appear on the live site (or even on dev).
They are:

1. Teacher Forum - the link for this is - http://talkphysics.org/groups/5719
It works and we have about a dozen teachers in the group. If we link to it, and if we use it it will grow.
Please could you wire up this link with a suitable image (e.g. the quotation marks used on Lisa's page:
http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/general_pages/teacher_how_to2.json

Will add details of image for this.

2. Using isaac in your teaching. I'm making a page to be linked from here today, so please could you be ready to wire this up too. The file is called: teaching_with_isaac

http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/general_pages/teaching_with_isaac.json
Will add details of image for this.

**Comment by sacummins** [comment] 2015-08-10 14:09
Duplicate of #441

**Closed by sacummins** 2015-08-10 14:09 UTC
Labels: enhancement
