### ISSUE TITLE
MathJax rendering issue

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#497] opened 2015-09-02 15:19 UTC
Hi.

Justin has sent me this problem - one of the fractions in http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/questions/physics/mechanics/shm/level4/two_spring_SHM.json doesn't render properly: 
![image](https://cloud.githubusercontent.com/assets/6358545/9635432/5814a4aa-518e-11e5-9abe-f1838933f6de.png)

This seems to be consistent whenever he loads the page, and occurs on Chrome on Windows 7.

**Comment by sacummins** [comment] 2015-09-11 07:33
Unable to reproduce... It may have been fixed when we changed the maths font in this release?

I will close this issue but if it is still a problem please reopen.

**Closed by sacummins** 2015-09-11 07:33 UTC
