### ISSUE TITLE
Equation editor's tolerance

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#656] opened 2016-02-10 16:50 UTC
Compare the following situations:
![eqn_editor_issue](https://cloud.githubusercontent.com/assets/15194006/12954379/37aeb06e-d016-11e5-9bdd-cf1d7cdc09c2.png)
and
![eqn_editor_issue_1](https://cloud.githubusercontent.com/assets/15194006/12954384/3c49e71a-d016-11e5-89ac-9ad3c96301e2.png)

In the second case, the 2 is very slightly closer to v.  However, we might want the first input also to be recognized as m v^2/F.

**Comment by jsharkey13** [comment] 2016-02-12 13:07
Duplicate of #598

**Closed by jsharkey13** 2016-02-12 13:07 UTC
Labels: enhancement, equation_editor
