### ISSUE TITLE
Pre-ticked multiple choice questions

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#443] opened 2015-06-22 16:16 UTC
On questions with multiple accordion sections, a tick is appearing on the accordion section for multiple-choice questions before they have been answered. This might confuse users into not attempting this part of the question.

Example:
https://staging.isaacphysics.org/questions/pushing_wire_through_field_num

**Comment by jsharkey13** [comment] 2015-07-30 09:31
Duplicate of #384

**Closed** 2015-08-10 13:25 UTC
Labels: bug
